export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const GET_USER_ADDRESS_REQUEST = "GET_USER_ADDRESS_REQUEST";
export const GET_USER_ADDRESS_SUCCESS = "GET_USER_ADDRESS_SUCCESS";
export const ADD_DELIVERY_ADDRESS_SUCCESS = "ADD_DELIVERY_ADDRESS_SUCCESS";
export const ADD_USER_ADDRESS_SUCCESS = "ADD_USER_ADDRESS_SUCCESS";

export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";

export const SHOW_CATEGORY = "SHOW_CATEGORY";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";

export const SHOW_SUCCESS_MESSAGE = "SHOW_SUCCESS_MESSAGE";
export const SHOW_ERROR_MESSAGE = "SHOW_ERROR_MESSAGE";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";

export const RESET_USER = "RESET_USER";
export const RESET_SHIPMENT = "RESET_SHIPMENT";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";

export const CREATE_SHIPPING_ORDER_SUCCESS = "CREATE_SHIPPING_ORDER_SUCCESS";
export const GET_SHIPPED_ORDERS = "GET_SHIPPED_ORDERS";

export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_DETAILS = "GET_ORDER_DETAILS";
export const SHIPPED_ORDERS_DATA_REQUEST = "SHIPPED_ORDERS_DATA_REQUEST";
export const SHIPPED_ORDERS_DATA_SUCCESS = "SHIPPED_ORDERS_DATA_SUCCESS";

export const CREATE_SHIPMENT_ORDER_SUCCESS = "CREATE_SHIPMENT_ORDER_SUCCESS";
export const CREATE_SHIPMENT_ORDER_REQUEST = "CREATE_SHIPMENT_ORDER_REQUEST";

export const TRACK_ORDER_REQUEST = "TRACK_ORDER_REQUEST";
export const TRACK_ORDER_SUCCESS = "TRACK_ORDER_SUCCESS";
export const ORDER_DETAILS_UPDATED = "ORDER_DETAILS_UPDATED";
export const SHIPROCKET_SIGNIN_SUCCESS = "SHIPROCKET_SIGNIN_SUCCESS";
export const ORDER_SERVICEABILITY_REQUEST = "ORDER_SERVICEABILITY_REQUEST";
export const ORDER_SERVICEABILITY_SUCCESS = "ORDER_SERVICEABILITY_SUCCESS";

// new types added for warehouse
export const GET_WAREHOUSES_REQUEST = "GET_WAREHOUSES_REQUEST";
export const GET_WAREHOUSES_SUCCESS = "GET_WAREHOUSES_SUCCESS";
export const ADD_WAREHOUSE_REQUEST = "ADD_WAREHOUSE_REQUEST";
export const ADD_WAREHOUSE_SUCCESS = "ADD_WAREHOUSE_SUCCESS";
export const UPDATE_WAREHOUSE_REQUEST = "UPDATE_WAREHOUSE_REQUEST";
export const UPDATE_WAREHOUSE_SUCCESS = "UPDATE_WAREHOUSE_SUCCESS";
export const DELETE_WAREHOUSE_REQUEST = "DELETE_WAREHOUSE_REQUEST";
export const DELETE_WAREHOUSE_SUCCESS = "DELETE_WAREHOUSE_SUCCESS";

// new types added for emplooyee
export const GET_EMPLOYEES_REQUEST = "GET_EMPLOYEES_REQUEST";
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS";
export const DELETE_EMPLOYEE_REQUEST = "DELETE_EMPLOYEE_REQUEST";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
